services:
  # Modbus Server - Background Service
  - type: pserv
    name: modbus-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python modbus_server_simulation.py
    envVars:
      - key: MODBUS_SERVER_IP
        value: "0.0.0.0"
      - key: MODBUS_SERVER_PORT
        value: "5020"
    port: 8080 # Expose the dummy HTTP port

  # FastAPI Client - Web Service
  - type: web
    name: fastapi-client
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_client:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MODBUS_SERVER_IP
        value: "modbus-server"
      - key: MODBUS_SERVER_PORT
        value: "5020"
