services:
  # Modbus Server service
  - type: pserv
    name: modbus-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python modbus_server_simulation.py
    envVars:
      - key: MODBUS_SERVER_IP
        value: "0.0.0.0"
      - key: MODBUS_SERVER_PORT
        value: "5020"

  # FastAPI Client service
  - type: web
    name: fastapi-client
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_client:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODBUS_SERVER_IP
        value: "modbus-server" # Use internal Render service name
      - key: MODBUS_SERVER_PORT
        value: "5020"
